server:
  port: ${PORT:8080}

spring:
  thymeleaf:
    cache: true

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}&sslmode=require&channelBinding=require

  jpa:
    show-sql: false

logging:
  config: classpath:logback-spring.xml
  level:
    com.tuganire: WARN
    org.springframework: WARN
